CREATE TABLE accounts
(
    id          bigint generated by default as identity primary key,
    holder_name varchar(100)   not null,
    balance     numeric(19, 2) not null default 0 check (balance >= 0),
    created_at  timestamptz    not null
);

CREATE TABLE ledger_entries
(
    id            bigint generated by default as identity primary key,
    account_id    bigint         not null references accounts (id),
    type          varchar(10)    not null check (type in ('CREDIT', 'DEBIT')),
    amount        numeric(19, 2) not null check (amount > 0),
    description   varchar(255)   not null,
    balance_after numeric(19, 2) not null,
    created_at    timestamptz    not null
);

CREATE INDEX idx_ledger_entries_account_id ON ledger_entries (account_id);
