spring.application.name=ledger

spring.datasource.url=jdbc:postgresql://localhost:5431/ledger
spring.datasource.username=ledger
spring.datasource.password=ledger

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
